# NumPy Library

In [30]:
import numpy as np

In [ ]:
#Indexing
arr = np.array([1, 2, 3, 4])

print(arr[2] + arr[3])

In [ ]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st dim: ', arr[0, 1])

In [ ]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('5th element on 2nd dim: ', arr[1, 4])

In [ ]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -1])

In [ ]:
#Slicing
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[4:])

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[:4])

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1])

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[::2])

In [ ]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])

In [58]:
# Practice Slicing
arr_2d = np.array([[0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14],[15,16,17,18,19]])
arr_2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [70]:
arr_2d[0:2,1:3]

array([[1, 2],
       [6, 7]])

In [33]:
#Data Types
arr = np.array(['apple', 'banana', 'cherry'])

arr.dtype

dtype('<U6')

In [34]:
arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [35]:
arr = np.array([1, 2, 3, 4], dtype='i4')

print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [ ]:
arr = np.array([1, 0, 3])

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)

In [2]:
arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype(int)

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [3]:
#Copy And View
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [4]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)


[42  2  3  4  5]
[42  2  3  4  5]


In [5]:
#Shape
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)


(2, 4)


In [6]:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


In [12]:
arr = np.array([[1, 2, 3, 4],[5, 6, 7, 8]])

print(arr)
print('shape of array :', arr.shape)

[[1 2 3 4]
 [5 6 7 8]]
shape of array : (2, 4)


In [37]:
#Reshaping
arr = np.array([1,2,3,4,5,6,7,8])
new = arr.reshape((4,2))
print(new,"\n")
new2 = arr.reshape((2,4))
print(new2)

[[1 2]
 [3 4]
 [5 6]
 [7 8]] 

[[1 2 3 4]
 [5 6 7 8]]


In [13]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)

print(newarr)

[1 2 3 4 5 6]


In [14]:
#Iterations
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
    print(x)


[1 2 3]
[4 5 6]


In [15]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
    print(x)


[1 2 3]
[4 5 6]


In [17]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
    for y in x:
        for z in y:
            print(z)


1
2
3
4
5
6
7
8
9
10
11
12


In [19]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(arr.shape)
for x in np.nditer(arr):
    print(x)

(2, 2, 2)
1
2
3
4
5
6
7
8


In [20]:
#Joining And Concatenating
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [29]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

print(arr1,"\n")
print(arr2, "\n")
arr3 = np.concatenate((arr1, arr2), axis=1)
arr4 = np.concatenate((arr1, arr2), axis=0)

print(arr3,"\n",arr3.shape,"\n")
print(arr4,"\n",arr4.shape)

[[1 2]
 [3 4]] 

[[5 6]
 [7 8]] 

[[1 2 5 6]
 [3 4 7 8]] 
 (2, 4) 

[[1 2]
 [3 4]
 [5 6]
 [7 8]] 
 (4, 2)


In [38]:
#Joining through Stack
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [39]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=0)

print(arr)

[[1 2 3]
 [4 5 6]]


In [40]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [41]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print(arr)


[[1 2 3]
 [4 5 6]]


In [42]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))

print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


In [46]:
arr1 = np.array([[1, 2, 3],[7, 8, 9]])

arr2 = np.array([[4, 5, 6],[10, 11, 12]])

arr = np.dstack((arr1, arr2))

print(arr)

[[[ 1  4]
  [ 2  5]
  [ 3  6]]

 [[ 7 10]
  [ 8 11]
  [ 9 12]]]


In [51]:
#Ravel
arr1 = np.array([[1, 2, 3],[7, 8, 9]])
rav = arr1.ravel()
rav[0]=10
print(rav)

[10  2  3  7  8  9]


In [52]:
arr1 #Changes the original

array([[10,  2,  3],
       [ 7,  8,  9]])

In [53]:
#Flatten
arr1 = np.array([[1, 2, 3],[7, 8, 9]])
flat = arr1.flatten()
flat[0]=10
print(flat)
print("\n",arr1) #Do not change the original

[10  2  3  7  8  9]

 [[1 2 3]
 [7 8 9]]
