In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_excel('pracitce1.xlsx')
data

Dataset
0    117313
1    104002
2    113038
3    101936
4     84560
5    113136
6     80740
7    100536
8    105052
9     87201
10    91986
11    94868
12    90745
13   102848
14    85927
15   112276
16   108637
17    96818
18    92307
19   114564
20   109714
21   108833
22   115295
23    89279
24    81720
25    89344
26   114426
27    90410
28    95118
29   113382

In [3]:
sample_mean = round(data.mean() , 2)
mue = 113000

In [4]:
std_pop = 15000
sample_size = 30

In [5]:
std_error = round(std_pop / 30**.5,1)
std_error

2738.6

In [6]:
z = 1.96

In [7]:
Z = round((sample_mean - mue) / std_error , 2)
Z = Z[0]
Z

-4.67

In [8]:
if Z != z:
    print("hypothesis Rejected")
else:
    print("hypothesis Accepted")

hypothesis Rejected


In [9]:
data1 = pd.read_excel("practice2.xlsx")*100
data1

Open rate
0       26.0
1       23.0
2       42.0
3       49.0
4       23.0
5       59.0
6       29.0
7       29.0
8       57.0
9       40.0

In [10]:
sample_mean = round(data1.mean(),2)
std_daviation = 13.74

In [11]:
sample_mean

Open rate    37.7
dtype: float64

In [12]:
std_error =round(std_daviation / 10**.5,2)
std_error

4.34

In [43]:
from scipy.stats import ttest_1samp

In [44]:
T = (sample_mean - 40) / std_error
abs(T)

Open rate    0.529954
dtype: float64

In [54]:
ttest,pvalue2= ttest_1samp(data1 , 40)

In [55]:
one_tail_pvalue = pvalue2/2
one_tail_pvalue

array([0.30463414])

In [56]:
pvalue2

array([0.60926829])

In [58]:
if  abs(ttest)< 2.82:
    print("hypothesis accepted at 99%")
elif abs(ttest)< 1.83:
    print("Hypothesis accept at 95%")
else:
    print("Hypothesis rejected")

hypothesis accepted at 99%


In [57]:
ttest

array([-0.52950182])